#!/bin/bash

(
  cd "$(dirname "$0")"

  file_start=$(cat CMakeLists.txt | grep -n '#begin je2be-desktop' | cut -f1 -d:)
  file_end=$(cat CMakeLists.txt | grep -n '#end je2be-desktop' | cut -f1 -d:)

  tmp=$(mktemp)

  cat CMakeLists.txt | head -n $file_start > "$tmp"
  git ls-files | grep -e ^include -e ^src | sed 's:\(.*\):  \1:g' >> "$tmp"
  cat CMakeLists.txt | tail -n +${file_end} >> "$tmp"

  mv -f "$tmp" CMakeLists.txt

  (cd ext/je2be && make update-cmakelists)
  (cd ext/je2be/deps/libminecraft-file && ./ls-files)
)
