#!/bin/bash

(
  cd "$(dirname "$0")"

  file_start=$(cat CMakeLists.txt | grep -n '#begin je2be-gui' | cut -f1 -d:)
  file_end=$(cat CMakeLists.txt | grep -n '#end je2be-gui' | cut -f1 -d:)

  tmp=$(mktemp)

  cat CMakeLists.txt | head -n $file_start > "$tmp"
  git ls-files | grep -e ^include -e ^src | sed 's:\(.*\):  \1:g' >> "$tmp"
  cat CMakeLists.txt | tail -n +${file_end} >> "$tmp"

  mv -f "$tmp" CMakeLists.txt
)
